Internal Server Error: /auth/token/login/
Traceback (most recent call last):
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\djoser\utils.py", line 38, in post
    return self._action(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\djoser\views.py", line 24, in _action
    token = utils.login_user(self.request, serializer.user)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\djoser\utils.py", line 17, in login_user
    token, _ = settings.TOKEN_MODEL.objects.get_or_create(user=user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Token' has no attribute 'objects'
"POST /auth/token/login/ HTTP/1.1" 500 103278
Internal Server Error: /auth/token/login/
Traceback (most recent call last):
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\djoser\utils.py", line 38, in post
    return self._action(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\djoser\views.py", line 24, in _action
    token = utils.login_user(self.request, serializer.user)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\djoser\utils.py", line 17, in login_user
    token, _ = settings.TOKEN_MODEL.objects.get_or_create(user=user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Token' has no attribute 'objects'
"POST /auth/token/login/ HTTP/1.1" 500 103278
Internal Server Error: /auth/token/login
Traceback (most recent call last):
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\djoser\utils.py", line 38, in post
    return self._action(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\djoser\views.py", line 24, in _action
    token = utils.login_user(self.request, serializer.user)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\djoser\utils.py", line 17, in login_user
    token, _ = settings.TOKEN_MODEL.objects.get_or_create(user=user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Token' has no attribute 'objects'
"POST /auth/token/login HTTP/1.1" 500 103259
Internal Server Error: /auth/token/login/
Traceback (most recent call last):
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\djoser\utils.py", line 38, in post
    return self._action(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\djoser\views.py", line 24, in _action
    token = utils.login_user(self.request, serializer.user)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\djoser\utils.py", line 17, in login_user
    token, _ = settings.TOKEN_MODEL.objects.get_or_create(user=user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Token' has no attribute 'objects'
"POST /auth/token/login/ HTTP/1.1" 500 103278
Internal Server Error: /auth/token/login
Traceback (most recent call last):
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\djoser\utils.py", line 38, in post
    return self._action(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\djoser\views.py", line 24, in _action
    token = utils.login_user(self.request, serializer.user)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\djoser\utils.py", line 17, in login_user
    token, _ = settings.TOKEN_MODEL.objects.get_or_create(user=user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Token' has no attribute 'objects'
"POST /auth/token/login HTTP/1.1" 500 103699
Internal Server Error: /tickets/
Traceback (most recent call last):
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: companies_company.logo

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 727, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 699, in get_context
    'post_form': self.get_rendered_html_form(data, view, 'POST', request),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 508, in get_rendered_html_form
    return self.render_form_for_serializer(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 518, in render_form_for_serializer
    return form_renderer.render(
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 372, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\templatetags\rest_framework.py", line 86, in render_field
    return renderer.render_field(field, style)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 351, in render_field
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\defaulttags.py", line 194, in render
    values = self.sequence.resolve(context, ignore_failures=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 718, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 917, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\relations.py", line 215, in iter_options
    self.get_choices(cutoff=self.html_cutoff),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\relations.py", line 202, in get_choices
    self.to_representation(item): self.display_value(item) for item in queryset
                                                                       ^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: companies_company.logo
"GET /tickets/ HTTP/1.1" 500 318364
Internal Server Error: /tickets/
Traceback (most recent call last):
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: companies_company.logo

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 727, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 699, in get_context
    'post_form': self.get_rendered_html_form(data, view, 'POST', request),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 508, in get_rendered_html_form
    return self.render_form_for_serializer(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 518, in render_form_for_serializer
    return form_renderer.render(
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 372, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\templatetags\rest_framework.py", line 86, in render_field
    return renderer.render_field(field, style)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 351, in render_field
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\defaulttags.py", line 194, in render
    values = self.sequence.resolve(context, ignore_failures=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 718, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 917, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\relations.py", line 215, in iter_options
    self.get_choices(cutoff=self.html_cutoff),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\relations.py", line 202, in get_choices
    self.to_representation(item): self.display_value(item) for item in queryset
                                                                       ^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: companies_company.logo
"GET /tickets/ HTTP/1.1" 500 318501
Internal Server Error: /tickets/
Traceback (most recent call last):
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: companies_company.logo

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 727, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 699, in get_context
    'post_form': self.get_rendered_html_form(data, view, 'POST', request),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 508, in get_rendered_html_form
    return self.render_form_for_serializer(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 518, in render_form_for_serializer
    return form_renderer.render(
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 372, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\templatetags\rest_framework.py", line 86, in render_field
    return renderer.render_field(field, style)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 351, in render_field
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\defaulttags.py", line 194, in render
    values = self.sequence.resolve(context, ignore_failures=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 718, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 917, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\relations.py", line 215, in iter_options
    self.get_choices(cutoff=self.html_cutoff),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\relations.py", line 202, in get_choices
    self.to_representation(item): self.display_value(item) for item in queryset
                                                                       ^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: companies_company.logo
"GET /tickets/ HTTP/1.1" 500 318501
Internal Server Error: /tickets/
Traceback (most recent call last):
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: companies_company.logo

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 727, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 699, in get_context
    'post_form': self.get_rendered_html_form(data, view, 'POST', request),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 508, in get_rendered_html_form
    return self.render_form_for_serializer(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 518, in render_form_for_serializer
    return form_renderer.render(
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 372, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\templatetags\rest_framework.py", line 86, in render_field
    return renderer.render_field(field, style)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 351, in render_field
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\defaulttags.py", line 194, in render
    values = self.sequence.resolve(context, ignore_failures=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 718, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 917, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\relations.py", line 215, in iter_options
    self.get_choices(cutoff=self.html_cutoff),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\relations.py", line 202, in get_choices
    self.to_representation(item): self.display_value(item) for item in queryset
                                                                       ^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: companies_company.logo
"GET /tickets/ HTTP/1.1" 500 318501
Internal Server Error: /tickets/
Traceback (most recent call last):
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: companies_company.logo

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 727, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 699, in get_context
    'post_form': self.get_rendered_html_form(data, view, 'POST', request),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 508, in get_rendered_html_form
    return self.render_form_for_serializer(serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 518, in render_form_for_serializer
    return form_renderer.render(
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 372, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\templatetags\rest_framework.py", line 86, in render_field
    return renderer.render_field(field, style)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\renderers.py", line 351, in render_field
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\defaulttags.py", line 194, in render
    values = self.sequence.resolve(context, ignore_failures=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 718, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\template\base.py", line 917, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\relations.py", line 215, in iter_options
    self.get_choices(cutoff=self.html_cutoff),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\rest_framework\relations.py", line 202, in get_choices
    self.to_representation(item): self.display_value(item) for item in queryset
                                                                       ^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\models\query.py", line 400, in __iter__
    self._fetch_all()
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub Repositories\django-ticketing\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: companies_company.logo
"GET /tickets/ HTTP/1.1" 500 318501
